MagicVilla_Web/Controllers/UserController.cs
using Magic_Villa_Web.Models;
using MagicVilla_Web.Models.DTO;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using Utility;

namespace MagicVilla_Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IAuthServices _authServices;
        public UserController(IAuthServices authServices)
        {
            _authServices = authServices;
        }
        public IActionResult Login()
        {
            LoginRequestDto obj = new();
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginRequestDto obj)
        {
            APIResponse res = await _authServices.LoginAsync<APIResponse>(obj);
            if (res != null && res.IsSuccess)
            {
                LoginResponseDto model = JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(res.Result));

                var handler = new JwtSecurityTokenHandler();
                var jwt = handler.ReadJwtToken(model.Token);

                //becouse we dont need to login again when we select to do any operation,(save the login detealis)
                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name,model.user.UserName));
                identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(u=>u.Type =="role").Value));
                var princple = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,princple);

                //this lines for token and send it to the authantication operagions
                HttpContext.Session.SetString(SD.SessionToken,model.Token);
                return RedirectToAction("Index", "Home");
                
            }
            else
            {
                ModelState.AddModelError("CustomError",res.ErrorMessages.FirstOrDefault());
                return View(obj);
            }
        }

        public IActionResult Register()
        {
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text = SD.Admin , Value=SD.Admin},
                new SelectListItem{Text = SD.Customer , Value=SD.Customer}
            };
            ViewBag.RoleList = roleList;    
            RegistrationRequestDto obj = new();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegistrationRequestDto obj)
        {
            if (string.IsNullOrEmpty(obj.Role))
            {
                obj.Role = SD.Customer;
            }
            APIResponse res = await _authServices.RegisterAsync<APIResponse>(obj);
            if (res != null && res.IsSuccess)
            {
                return RedirectToAction("Login");
            }
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text = SD.Admin , Value=SD.Admin},
                new SelectListItem{Text = SD.Customer , Value=SD.Customer}
            };
            ViewBag.RoleList = roleList;
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            HttpContext.Session.SetString(SD.SessionToken, "");
            return RedirectToAction("Index","Home");
        }

        public IActionResult AccessDenied() 
        {
                return View();
        }
    }
}

MagicVilla_Web/Controllers/VillaController.cs
using AutoMapper;
using AutoMapper.Configuration.Conventions;
using Magic_Villa_Web.Models;
using Magic_Villa_Web.Models.DTO;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using Utility;

namespace MagicVilla_Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IVillaServices _services;
        private readonly IMapper _mapper;
        public VillaController(IVillaServices services,IMapper mapper)
        {
            _services = services;
            _mapper = mapper;
        }
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> IndexVilla()
        {
            List<VillaDto> list = new();
            var response = await _services.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(response.Result));
            }
            return View(list);
        }
        [Authorize(Roles ="admin")]
        public async Task<ActionResult> CreateVilla()
        {
            return View();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateVilla(VillaCreatedDto model)
        {
            if (ModelState.IsValid)
            {
                 var response = await _services.CreateAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Villa Created Successfully!";
                    return RedirectToAction(nameof(IndexVilla));
                }

            }
            TempData["error"] = "Error Encountered!";

            return View(model);
        }

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> UpdateVilla(int villaId)
		{
				var response = await _services.GetAsync<APIResponse>(villaId, HttpContext.Session.GetString(SD.SessionToken));
				if (response != null && response.IsSuccess)
				{
                    VillaDto dto = JsonConvert.DeserializeObject<VillaDto>(Convert.ToString(response.Result));
                VillaUpdatedDto model = _mapper.Map<VillaUpdatedDto>(dto);

					return View(model); 
				
				}

			return NotFound();
		}
        
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
		public async Task<ActionResult> UpdateVilla(VillaUpdatedDto model)
		{
            if (ModelState.IsValid)
            {
                var response = await _services.UpdateAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Villa Updated Successfully!";

                    return RedirectToAction(nameof(IndexVilla));
                }
            }
            TempData["error"] = "Error Encountered!";


            return View(model);
		}

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> DeleteVilla(int villaId)
		{
			var response = await _services.GetAsync<APIResponse>(villaId, HttpContext.Session.GetString(SD.SessionToken));
			if (response != null && response.IsSuccess)
			{
				VillaDto dto = JsonConvert.DeserializeObject<VillaDto>(Convert.ToString(response.Result));

				return View(dto);
			}

			return NotFound();
		}

        [Authorize(Roles = "admin")]
        [HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> DeleteVilla(VillaDto model) 
        { 
			var response = await _services.RemoveAsync<APIResponse>(model.Id, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Villa Deleted Successfully!";
                return RedirectToAction(nameof(IndexVilla));
            }
            TempData["error"] = "Error Encountered!";


            return View(model);
		}
	}
}

MagicVilla_Web/Controllers/VillaNumberController.cs
using AutoMapper;
using AutoMapper.Configuration.Conventions;
using Magic_Villa_Web.Models;
using Magic_Villa_Web.Models.DTO;
using MagicVilla_Web.Models.VillaNumberModels;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Collections.Generic;
using Utility;

namespace MagicVilla_Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IVillaNumberServices _services;
        private readonly IVillaServices _villaservices;

        private readonly IMapper _mapper;
        public VillaNumberController(IVillaNumberServices services,IMapper mapper, IVillaServices villaservices)
        {
            _services = services;
            _mapper = mapper;
            _villaservices = villaservices;
        }
        public async Task<ActionResult> IndexVillaNumber()
        {
            List<VillaNumberDto> list = new();
            var response = await _services.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<VillaNumberDto>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

        [Authorize(Roles = "admin")]

        public async Task<ActionResult> CreateVillaNumber()
        {
            VillaNumberCreateVM villanumber = new();
            var response = await _villaservices.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                    villanumber.villalist = JsonConvert.DeserializeObject<List<VillaDto>>
                                            (Convert.ToString(response.Result)).Select(i => new SelectListItem
                                            {
                                                Text = i.Name,
                                                Value = i.Id.ToString()
                                            });   
            }
            return View(villanumber);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateVillaNumber(VillaNumberCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var respone =await _services.CreateAsync<APIResponse>(model.VillaNumber, HttpContext.Session.GetString(SD.SessionToken));
                if (respone != null && respone.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
                else
                {
                    if(respone.ErrorMessages.Count >0)
                    {
                        ModelState.AddModelError("ErrorMessages", respone.ErrorMessages.FirstOrDefault());
                    }
                }

            }
            var resp = await _villaservices.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (resp != null && resp.IsSuccess)
            {
                model.villalist = JsonConvert.DeserializeObject<List<VillaDto>>
                                        (Convert.ToString(resp.Result)).Select(i => new SelectListItem
                                        {
                                            Text = i.Name,
                                            Value = i.Id.ToString()
                                        });
            }
            return View(model);
        }

        [Authorize(Roles = "admin")]

        public async Task<ActionResult> UpdateVillaNumber(int villaNum)
        {
            VillaNumberUpdateVM villanumber = new();
            var response1 = await _villaservices.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response1 != null && response1.IsSuccess)
            {
                villanumber.villalist = JsonConvert.DeserializeObject<List<VillaDto>>
                                        (Convert.ToString(response1.Result)).Select(i => new SelectListItem
                                        {
                                            Text = i.Name,
                                            Value = i.Id.ToString()
                                        });
            }
            var response = await _services.GetAsync<APIResponse>(villaNum, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                villanumber.VillaNumber = JsonConvert.DeserializeObject<VillaNumberUpdatedDto>(Convert.ToString(response.Result));
                return View(villanumber);

            }

            return NotFound();
        }

        [Authorize(Roles = "admin")]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UpdateVillaNumber(VillaNumberUpdateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _services.UpdateAsync<APIResponse>(model.VillaNumber, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }
            return View(model);
        }


        [Authorize(Roles = "admin")]

        public async Task<ActionResult> DeleteVillaNumber(int villaNum)
        {
            VillaNumberDeleteVM villanumber = new();
            var response1 = await _villaservices.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response1 != null && response1.IsSuccess)
            {
                villanumber.villalist = JsonConvert.DeserializeObject<List<VillaDto>>
                                        (Convert.ToString(response1.Result)).Select(i => new SelectListItem
                                        {
                                            Text = i.Name,
                                            Value = i.Id.ToString()
                                        });
            }
            var response = await _services.GetAsync<APIResponse>(villaNum, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                VillaNumberDto model = JsonConvert.DeserializeObject<VillaNumberDto>(Convert.ToString(response.Result));
                villanumber.VillaNumber = model;
                return View(villanumber);

            }

            return NotFound();
        }

        [Authorize(Roles = "admin")]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteVillaNumber(VillaNumberDeleteVM model)
        {
            var response = await _services.RemoveAsync<APIResponse>(model.VillaNumber.VillaNo, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(IndexVillaNumber));
            }

            return View(model);
        }
    }
}

MagicVilla_Web/Views/Shared/_Layout.cshtml
@using Utility;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MagicVilla_Web</title>
    <link rel="stylesheet" href="~/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MagicVilla_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <style>
        .nav-link.dropdown-toggle {
            color: white; /* Change the color to black or any other desired color */
        }
    </style>

</head>
<body>
    <partial name="_Notifications" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow my-1">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MagicVilla_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @if (User.IsInRole(SD.Admin))
                                {
                                    <span>Content Mangement</span>
                                }
                                else
                                {
                                    <span>Villa & Villa Numbers</span>
                                }
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="VillaNumber" asp-action="IndexVillaNumber">Villa Number</a>
                                </li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Villa" asp-action="IndexVilla">Villa</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class ="navbar">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="#" style="margin-right:30px ; color: white">Hello, @User.Identity.Name</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="User" asp-action="Login" style="margin-right:30px;">Login</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area=""  asp-controller="User" asp-action="Register">Register</a>
                            </li>

                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MagicVilla_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MagicVilla_Web/Views/Shared/_Notifications.cshtml
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@if (TempData["success"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '@TempData["success"]',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        })
    </script>
}
@if (TempData["error"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        })
    </script>
}